### ISSUE TITLE
Please we need a demo project, in order to know how to implement SciDeJS in a Delphi project type (VCL, FMX, console, ...)

### ISSUE THREAD

**Issue by mercibac** [Mikanoshi/SciDeJS#1]
You have done a great job by creating this bridge between Sciter and Delphi (the best of both worlds: Native applications with web technologies). 

In order to build real world projects, we need a demo (sample) project to understand the architecture of the SciDeJS <-> Delphi relation.

Thanks in advance !

**Comment by Mikanoshi** [comment]
Sciter.TIS example can be found here:
https://code.highspec.ru/Mikanoshi/RnQ

JavaScript version is not that different, I almost finished JS version of R&Q and will release it some time in the future :)
Wrapper has no Assets/SOM support that exposes native classes to Sciter's scripting engine, so interaction is done using ValueNativeFunctorSet() to access native methods in script and SciterCall()/SciterCallScriptingMethod()/SciterCallScriptingFunction() to access script methods from native side.

**Comment by mercibac** [comment]
Thanks ! 

These demos are beautiful and very well designed. I'm still tuned for the JS version of R&Q. In the meantime, I will check the TIS example's architecture.

**Comment by Mikanoshi** [comment]
Released:
https://code.highspec.ru/Mikanoshi/RnQ/src/branch/master/RnQ/SciterLib.pas
I removed all VCL forms and am running a message loop manually:
https://code.highspec.ru/Mikanoshi/RnQ/src/branch/master/RnQ/RnQx64.dpr#L141
Sciter is loaded into invisible window that is created by the wrapper, all other windows are created from JS.
