### ISSUE TITLE
debug mode compilation error

### ISSUE THREAD

**Issue by idigger** [Mikanoshi/SciDeJS#2]
debug mode compilation error
![11111111](https://github.com/Mikanoshi/SciDeJS/assets/2608116/bcf2518f-4e2b-4f97-bdb5-7370f0d47c52)

**Comment by Mikanoshi** [comment]
It makes these enums 4 bytes in size, but it really should be MAXINT instead of $FFFFFFFF like in all others. Even better is to remove it and wrap enum into {$Z4} ... {$Z1} compiler directives to set the required size. You also can just disable range checks in your Debug config.

**Comment by idigger** [comment]
Problem solved, thanks
